root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/app"
pre_cmd = ["cd frontend && pnpm generate"]
cmd = "go build -o ./tmp/app cmd/cli/*.go"
post_cmd = []
full_bin = ""
args_bin = []
include_file = []
include_dir = []
include_ext = ["go", "html", "ts", "vue"]
exclude_file = []
exclude_dir = ["bin", "tmp", "vendor", "frontend/node_modules"]
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
log = "air.log"
poll = false
poll_interval = 0
send_interrupt = false
stop_on_error = true
delay = 1000
kill_delay = 500
rerun = false
rerun_delay = 500

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = false

[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = false
keep_scroll = true
