-- +goose Up
-- +goose StatementBegin

CREATE TABLE IF NOT EXISTS altalune_projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(20) NOT NULL,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(100),
    timezone VARCHAR(50) NOT NULL,
    environment VARCHAR(50) NOT NULL DEFAULT 'sandbox',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_altalune_projects_environment CHECK (environment IN ('live', 'sandbox'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_altalune_projects_public_id ON altalune_projects (public_id);

CREATE TABLE IF NOT EXISTS altalune_project_api_keys (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(20) NOT NULL,
    project_id INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    expiration TIMESTAMPTZ NOT NULL,
    key VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_altalune_project_api_keys_project_id
        FOREIGN KEY (project_id) REFERENCES altalune_projects (id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_altalune_project_api_keys_public_id ON altalune_project_api_keys (public_id);

-- (Opsional) enforce uniqueness system-wide untuk API key string:
CREATE UNIQUE INDEX IF NOT EXISTS ux_altalune_project_api_keys_key ON altalune_project_api_keys (key);

-- Index untuk mempercepat query by project_id:
CREATE INDEX IF NOT EXISTS ix_altalune_project_api_keys_project_id ON altalune_project_api_keys (project_id);

-- Trigger function (satu kali saja; IF NOT EXISTS untuk function tidak native, jadi cek manual kalau perlu)
CREATE OR REPLACE FUNCTION set_timestamp()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_altalune_projects_updated
BEFORE UPDATE ON altalune_projects
FOR EACH ROW EXECUTE FUNCTION set_timestamp();

CREATE TRIGGER trg_altalune_project_api_keys_updated
BEFORE UPDATE ON altalune_project_api_keys
FOR EACH ROW EXECUTE FUNCTION set_timestamp();

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

-- Drop triggers
DROP TRIGGER IF EXISTS trg_altalune_project_api_keys_updated ON altalune_project_api_keys;
DROP TRIGGER IF EXISTS trg_altalune_projects_updated ON altalune_projects;

-- Drop tables (indexes & constraints ikut terhapus)
DROP TABLE IF EXISTS altalune_project_api_keys;
DROP TABLE IF EXISTS altalune_projects;

-- Drop function (kalau tidak dipakai di tempat lain)
DROP FUNCTION IF EXISTS set_timestamp();

-- +goose StatementEnd
