-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS altalune_projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(20) NOT NULL,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(100),
  timezone VARCHAR(50) NOT NULL,
  environment VARCHAR(50) NOT NULL DEFAULT 'sandbox',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_altalune_projects_environment CHECK (environment IN ('live', 'sandbox'))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_altalune_projects_public_id ON altalune_projects (public_id);

CREATE TABLE IF NOT EXISTS altalune_project_api_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  public_id VARCHAR(20) NOT NULL,
  project_id BIGINT NOT NULL,
  name VARCHAR(50) NOT NULL,
  expiration TIMESTAMPTZ NOT NULL,
  key VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- Composite primary key including partition key
  PRIMARY KEY (project_id, id),
  CONSTRAINT fk_altalune_project_api_keys_project_id
    FOREIGN KEY (project_id) REFERENCES altalune_projects (id)
    ON DELETE CASCADE ON UPDATE CASCADE
) PARTITION BY LIST (project_id);

-- Include project_id in unique indexes for partitioned table
CREATE UNIQUE INDEX IF NOT EXISTS ux_altalune_project_api_keys_public_id 
  ON altalune_project_api_keys (project_id, public_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_altalune_project_api_keys_key 
  ON altalune_project_api_keys (project_id, key);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- Drop tables (partitions, indexes & constraints will be dropped automatically)
DROP TABLE IF EXISTS altalune_project_api_keys;
DROP TABLE IF EXISTS altalune_projects;
-- +goose StatementEnd
