-- +goose Up
-- +goose StatementBegin

-- =============================================================================
-- EMAIL VERIFICATION & OTP TOKENS MIGRATION
-- =============================================================================
-- This migration adds support for:
-- 1. Email verification status tracking on users
-- 2. Email verification tokens for link-based verification
-- 3. OTP tokens for passwordless login
-- 4. Predefined 'user' role (global) with 'dashboard:read' permission
-- 5. Fix project_members role constraint (remove 'viewer', keep 'user')
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Extend altalune_users table with email verification columns
-- -----------------------------------------------------------------------------
ALTER TABLE altalune_users
ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN activated_at TIMESTAMPTZ;

-- Index for filtering by email_verified status
CREATE INDEX IF NOT EXISTS idx_users_email_verified ON altalune_users (email_verified);

-- -----------------------------------------------------------------------------
-- 2. Create altalune_email_verification_tokens table
-- -----------------------------------------------------------------------------
-- Stores hashed verification tokens sent to user emails
-- token_hash: SHA256 hash of the actual token (64-char hex string)
-- used_at: Soft-delete pattern for audit trail
CREATE TABLE altalune_email_verification_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES altalune_users(id) ON DELETE CASCADE,
  token_hash VARCHAR(64) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ux_email_verification_token UNIQUE (token_hash)
);

-- Index for user lookup (to invalidate existing tokens)
CREATE INDEX ix_email_verification_user_id ON altalune_email_verification_tokens(user_id);

-- Partial index for valid (unused) tokens - improves lookup performance
CREATE INDEX ix_email_verification_expires ON altalune_email_verification_tokens(expires_at)
  WHERE used_at IS NULL;

-- -----------------------------------------------------------------------------
-- 3. Create altalune_otp_tokens table
-- -----------------------------------------------------------------------------
-- Stores hashed OTP codes for passwordless authentication
-- email: Used instead of user_id for lookup before authentication
-- otp_hash: SHA256 hash of the 6-digit OTP code
CREATE TABLE altalune_otp_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  otp_hash VARCHAR(64) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for email lookup (OTP verification and rate limiting)
CREATE INDEX ix_otp_email ON altalune_otp_tokens(email);

-- Partial index for valid (unused) tokens
CREATE INDEX ix_otp_expires ON altalune_otp_tokens(expires_at) WHERE used_at IS NULL;

-- Index for rate limit queries (count recent OTPs by email)
CREATE INDEX ix_otp_email_created ON altalune_otp_tokens(email, created_at);

-- -----------------------------------------------------------------------------
-- 4. Seed 'user' role (global) with 'dashboard:read' permission
-- -----------------------------------------------------------------------------
-- Create 'user' role if not exists
INSERT INTO altalune_roles (public_id, name, description, created_at, updated_at)
VALUES (
  'senccaqawe976a',
  'user',
  'Default role for authenticated users',
  NOW(), NOW()
) ON CONFLICT (name) DO NOTHING;

-- Create 'dashboard:read' permission if not exists
INSERT INTO altalune_permissions (public_id, name, description, created_at, updated_at)
VALUES (
  'zhvlefub4pgxgg',
  'dashboard:read',
  'Basic dashboard read access',
  NOW(), NOW()
) ON CONFLICT (name) DO NOTHING;

-- Link 'user' role to 'dashboard:read' permission
INSERT INTO altalune_roles_permissions (role_id, permission_id, created_at)
SELECT r.id, p.id, NOW()
FROM altalune_roles r, altalune_permissions p
WHERE r.name = 'user' AND p.name = 'dashboard:read'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- -----------------------------------------------------------------------------
-- 5. Fix project_members role constraint
-- -----------------------------------------------------------------------------
-- Per PROJECT_MEMBERSHIP_GUIDE.md, valid roles are: owner, admin, member, user
-- Remove 'viewer' from constraint as it's not used/documented
-- First migrate any existing 'viewer' roles to 'user' (safe transformation)
UPDATE altalune_project_members SET role = 'user' WHERE role = 'viewer';

-- Drop old constraint and add new one without 'viewer'
ALTER TABLE altalune_project_members
DROP CONSTRAINT IF EXISTS chk_project_members_role;

ALTER TABLE altalune_project_members
ADD CONSTRAINT chk_project_members_role
CHECK (role IN ('owner', 'admin', 'member', 'user'));

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

-- -----------------------------------------------------------------------------
-- Reverse all changes in proper order
-- -----------------------------------------------------------------------------

-- 1. Restore project_members constraint with 'viewer' (original state)
ALTER TABLE altalune_project_members
DROP CONSTRAINT IF EXISTS chk_project_members_role;

ALTER TABLE altalune_project_members
ADD CONSTRAINT chk_project_members_role
CHECK (role IN ('owner', 'admin', 'member', 'viewer', 'user'));

-- 2. Remove role-permission mapping (safe - just removes the link)
DELETE FROM altalune_roles_permissions
WHERE role_id = (SELECT id FROM altalune_roles WHERE name = 'user')
  AND permission_id = (SELECT id FROM altalune_permissions WHERE name = 'dashboard:read');

-- 3. Remove 'dashboard:read' permission if no other roles use it
DELETE FROM altalune_permissions
WHERE name = 'dashboard:read'
  AND NOT EXISTS (
    SELECT 1 FROM altalune_roles_permissions rp
    WHERE rp.permission_id = altalune_permissions.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM altalune_users_permissions up
    WHERE up.permission_id = altalune_permissions.id
  );

-- 4. Remove 'user' role if no users are assigned to it
DELETE FROM altalune_roles
WHERE name = 'user'
  AND NOT EXISTS (
    SELECT 1 FROM altalune_users_roles ur
    WHERE ur.role_id = altalune_roles.id
  );

-- 5. Drop OTP tokens table
DROP TABLE IF EXISTS altalune_otp_tokens;

-- 6. Drop email verification tokens table
DROP TABLE IF EXISTS altalune_email_verification_tokens;

-- 7. Remove columns from users table (drop index first)
DROP INDEX IF EXISTS idx_users_email_verified;
ALTER TABLE altalune_users DROP COLUMN IF EXISTS activated_at;
ALTER TABLE altalune_users DROP COLUMN IF EXISTS email_verified;

-- +goose StatementEnd
