-- +goose Up
-- +goose StatementBegin

-- =============================================================================
-- IAM CORE TABLES (GLOBAL - NON-PARTITIONED)
-- =============================================================================
-- CRITICAL: These tables are GLOBAL and do NOT include project_id columns.
-- They use simple primary keys (just id, not composite with project_id).
-- This differs from the partitioned table pattern used elsewhere in the system.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. altalune_users
-- -----------------------------------------------------------------------------
-- Global users table with OAuth-only authentication (no passwords)
-- Each user has a unique email and is assigned roles/permissions system-wide
CREATE TABLE IF NOT EXISTS altalune_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(20) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  is_active BOOLEAN NOT NULL DEFAULT true,
  email_verified BOOLEAN NOT NULL DEFAULT false,
  activated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_users_email_lowercase CHECK (email = LOWER(email))
);

-- Indexes for users table
CREATE INDEX IF NOT EXISTS idx_users_email ON altalune_users (email);
CREATE INDEX IF NOT EXISTS idx_users_is_active ON altalune_users (is_active);
CREATE INDEX IF NOT EXISTS idx_users_email_verified ON altalune_users (email_verified);

-- -----------------------------------------------------------------------------
-- 2. altalune_roles
-- -----------------------------------------------------------------------------
-- Global roles table (e.g., super_admin, developer, viewer)
-- Roles are assigned permissions and then users are assigned roles
CREATE TABLE IF NOT EXISTS altalune_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for roles table
CREATE INDEX IF NOT EXISTS idx_roles_name ON altalune_roles (name);

-- -----------------------------------------------------------------------------
-- 3. altalune_permissions
-- -----------------------------------------------------------------------------
-- Global permissions table with machine-readable names supporting colons
-- name: Machine-readable format (e.g., "project:read", "user:manage:delete")
-- description: Human-readable explanation for UI tooltips
-- effect: "allow" or "deny" (evaluation logic handled by middleware)
CREATE TABLE IF NOT EXISTS altalune_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL UNIQUE,
  effect VARCHAR(10) NOT NULL DEFAULT 'allow',
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_permissions_name CHECK (name ~ '^[a-zA-Z0-9_:]+$'),
  CONSTRAINT chk_permissions_effect CHECK (effect IN ('allow', 'deny'))
);

-- Indexes for permissions table
CREATE INDEX IF NOT EXISTS idx_permissions_name ON altalune_permissions (name);
CREATE INDEX IF NOT EXISTS idx_permissions_effect ON altalune_permissions (effect);

-- -----------------------------------------------------------------------------
-- 4. altalune_users_roles (Junction Table)
-- -----------------------------------------------------------------------------
-- Many-to-many relationship between users and roles
-- CASCADE DELETE: Removing user or role removes all mappings
CREATE TABLE IF NOT EXISTS altalune_users_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES altalune_users (id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES altalune_roles (id) ON DELETE CASCADE,
  UNIQUE (user_id, role_id)
);

-- Indexes for users_roles junction table
CREATE INDEX IF NOT EXISTS idx_users_roles_user_id ON altalune_users_roles (user_id);
CREATE INDEX IF NOT EXISTS idx_users_roles_role_id ON altalune_users_roles (role_id);

-- -----------------------------------------------------------------------------
-- 5. altalune_roles_permissions (Junction Table)
-- -----------------------------------------------------------------------------
-- Many-to-many relationship between roles and permissions
-- CASCADE DELETE: Removing role or permission removes all mappings
CREATE TABLE IF NOT EXISTS altalune_roles_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id BIGINT NOT NULL,
  permission_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (role_id) REFERENCES altalune_roles (id) ON DELETE CASCADE,
  FOREIGN KEY (permission_id) REFERENCES altalune_permissions (id) ON DELETE CASCADE,
  UNIQUE (role_id, permission_id)
);

-- Indexes for roles_permissions junction table
CREATE INDEX IF NOT EXISTS idx_roles_permissions_role_id ON altalune_roles_permissions (role_id);
CREATE INDEX IF NOT EXISTS idx_roles_permissions_permission_id ON altalune_roles_permissions (permission_id);

-- -----------------------------------------------------------------------------
-- 6. altalune_users_permissions (Junction Table)
-- -----------------------------------------------------------------------------
-- Many-to-many relationship for direct permission assignments to users
-- This allows assigning permissions directly to users (not through roles)
-- CASCADE DELETE: Removing user or permission removes all mappings
CREATE TABLE IF NOT EXISTS altalune_users_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  permission_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES altalune_users (id) ON DELETE CASCADE,
  FOREIGN KEY (permission_id) REFERENCES altalune_permissions (id) ON DELETE CASCADE,
  UNIQUE (user_id, permission_id)
);

-- Indexes for users_permissions junction table
CREATE INDEX IF NOT EXISTS idx_users_permissions_user_id ON altalune_users_permissions (user_id);
CREATE INDEX IF NOT EXISTS idx_users_permissions_permission_id ON altalune_users_permissions (permission_id);

-- -----------------------------------------------------------------------------
-- 7. altalune_project_members (Project Access)
-- -----------------------------------------------------------------------------
-- Manages which users have access to which projects and with what role
-- Project roles: owner, admin, member, viewer (simple hierarchy)
-- CASCADE DELETE: Removing project or user removes all memberships
CREATE TABLE IF NOT EXISTS altalune_project_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role VARCHAR(20) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (project_id) REFERENCES altalune_projects (id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES altalune_users (id) ON DELETE CASCADE,
  UNIQUE (project_id, user_id),
  CONSTRAINT chk_project_members_role CHECK (role IN ('owner', 'admin', 'member', 'viewer'))
);

-- Indexes for project_members table
CREATE INDEX IF NOT EXISTS idx_project_members_project_id ON altalune_project_members (project_id);
CREATE INDEX IF NOT EXISTS idx_project_members_user_id ON altalune_project_members (user_id);
CREATE INDEX IF NOT EXISTS idx_project_members_role ON altalune_project_members (role);

-- -----------------------------------------------------------------------------
-- 8. altalune_user_identities (OAuth Identities)
-- -----------------------------------------------------------------------------
-- Links users to external OAuth providers (Google, Github, etc.)
-- Supports multiple OAuth identities per user
-- CASCADE DELETE: Removing user removes all OAuth identity links
CREATE TABLE IF NOT EXISTS altalune_user_identities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(20) NOT NULL UNIQUE,
  user_id BIGINT NOT NULL,
  provider VARCHAR(50) NOT NULL,
  provider_user_id VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES altalune_users (id) ON DELETE CASCADE,
  UNIQUE (provider, provider_user_id)
);

-- Indexes for user_identities table
CREATE INDEX IF NOT EXISTS idx_user_identities_user_id ON altalune_user_identities (user_id);
CREATE INDEX IF NOT EXISTS idx_user_identities_provider ON altalune_user_identities (provider);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

-- Drop indexes first
DROP INDEX IF EXISTS idx_users_email_verified;

-- Drop junction tables first (they have foreign keys to entity tables)
DROP TABLE IF EXISTS altalune_user_identities;
DROP TABLE IF EXISTS altalune_project_members;
DROP TABLE IF EXISTS altalune_users_permissions;
DROP TABLE IF EXISTS altalune_roles_permissions;
DROP TABLE IF EXISTS altalune_users_roles;

-- Drop entity tables
DROP TABLE IF EXISTS altalune_permissions;
DROP TABLE IF EXISTS altalune_roles;
DROP TABLE IF EXISTS altalune_users;

-- +goose StatementEnd
