-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS altalune_chatbot_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  public_id VARCHAR(20) NOT NULL,
  project_id BIGINT NOT NULL,
  modules_config JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (project_id, id),
  CONSTRAINT fk_altalune_chatbot_configs_project_id
    FOREIGN KEY (project_id) REFERENCES altalune_projects (id)
    ON DELETE CASCADE ON UPDATE CASCADE
) PARTITION BY LIST (project_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_altalune_chatbot_configs_public_id
  ON altalune_chatbot_configs (project_id, public_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_altalune_chatbot_configs_project_id
  ON altalune_chatbot_configs (project_id);
-- +goose StatementEnd

-- Note: Partitions and default configs are created via lazy initialization in Go code.
-- - New projects: Partition + config created in project/repo.go Create() method
-- - Existing projects: Partition + config created on first API access in chatbot/repo.go GetByProjectID()

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS altalune_chatbot_configs CASCADE;
-- +goose StatementEnd
