-- +goose Up
-- +goose StatementBegin

-- =============================================================================
-- OAUTH SERVER TABLES - US5: OAuth Server Foundation
-- =============================================================================
-- This migration creates tables for Altalune to function as an OAuth 2.0
-- authorization server, allowing external applications (and the dashboard
-- itself) to use Altalune as an identity provider.
--
-- Architecture (follows Keycloak/Auth0 patterns):
-- - oauth_clients: GLOBAL - infrastructure-level, not project-scoped
-- - oauth_client_scopes: GLOBAL - maps clients to allowed scopes
-- - Authorization codes & refresh tokens: Global (cross-project user identity)
-- - Scopes: Global scope definitions
-- - Project members: Maps users to projects with roles
-- - user_identities tracks origin OAuth client for historical purposes
-- =============================================================================

-- -----------------------------------------------------------------------------
-- oauth_scopes (GLOBAL)
-- -----------------------------------------------------------------------------
-- Defines OAuth scopes that can be requested by clients
-- Standard scopes: openid, profile, email, offline_access
-- Custom project-specific scopes can be added later
CREATE TABLE IF NOT EXISTS altalune_oauth_scopes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(50) NOT NULL UNIQUE,
  description TEXT,
  is_standard BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_oauth_scopes_public_id
  ON altalune_oauth_scopes (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_oauth_scopes_name
  ON altalune_oauth_scopes (name);

CREATE INDEX IF NOT EXISTS idx_oauth_scopes_is_standard
  ON altalune_oauth_scopes (is_standard);

-- -----------------------------------------------------------------------------
-- oauth_clients (GLOBAL)
-- -----------------------------------------------------------------------------
-- Stores OAuth client applications that can authenticate users via Altalune
-- OAuth clients are infrastructure-level entities (like Auth0 Applications)
-- not project-scoped business data. This allows clients to serve users
-- across multiple projects.
-- Special case: Default dashboard client (is_default = true, pkce_required = true)
CREATE TABLE IF NOT EXISTS altalune_oauth_clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  client_id UUID NOT NULL UNIQUE,
  client_secret_hash VARCHAR(255) NOT NULL,
  redirect_uris TEXT[] NOT NULL,
  pkce_required BOOLEAN NOT NULL DEFAULT false,
  is_default BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_oauth_clients_redirect_uris_not_empty
    CHECK (array_length(redirect_uris, 1) > 0)
);

-- Unique index on client_id for fast lookups
CREATE UNIQUE INDEX IF NOT EXISTS ux_oauth_clients_client_id
  ON altalune_oauth_clients (client_id);

-- Unique index on public_id for API lookups
CREATE UNIQUE INDEX IF NOT EXISTS ux_oauth_clients_public_id
  ON altalune_oauth_clients (public_id);

-- Index for finding default clients
CREATE INDEX IF NOT EXISTS idx_oauth_clients_is_default
  ON altalune_oauth_clients (is_default) WHERE is_default = true;

-- -----------------------------------------------------------------------------
-- oauth_client_scopes (GLOBAL)
-- -----------------------------------------------------------------------------
-- Maps OAuth clients to allowed scopes
-- Determines what scopes a client can request
CREATE TABLE IF NOT EXISTS altalune_oauth_client_scopes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id UUID NOT NULL,
  scope_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (scope_id) REFERENCES altalune_oauth_scopes (id) ON DELETE CASCADE
);

-- Unique constraint: one scope per client
CREATE UNIQUE INDEX IF NOT EXISTS ux_oauth_client_scopes_client_scope
  ON altalune_oauth_client_scopes (client_id, scope_id);

-- Index for lookups by client_id
CREATE INDEX IF NOT EXISTS idx_oauth_client_scopes_client_id
  ON altalune_oauth_client_scopes (client_id);

-- -----------------------------------------------------------------------------
-- oauth_authorization_codes (GLOBAL)
-- -----------------------------------------------------------------------------
-- Stores short-lived authorization codes issued during OAuth flow
-- Soft-delete pattern: exchange_at timestamp marks when code was used
CREATE TABLE IF NOT EXISTS altalune_oauth_authorization_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code UUID NOT NULL UNIQUE,
  client_id UUID NOT NULL,
  user_id BIGINT NOT NULL,
  redirect_uri VARCHAR(500) NOT NULL,
  scope TEXT,
  nonce VARCHAR(100),
  code_challenge VARCHAR(128),
  code_challenge_method VARCHAR(10),
  expires_at TIMESTAMPTZ NOT NULL,
  exchange_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES altalune_users (id) ON DELETE CASCADE,
  CONSTRAINT chk_oauth_authorization_codes_challenge_method
    CHECK (code_challenge_method IS NULL OR code_challenge_method IN ('S256', 'plain'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_oauth_authorization_codes_code
  ON altalune_oauth_authorization_codes (code);

-- Partial index for active (non-exchanged) codes only
CREATE INDEX IF NOT EXISTS idx_oauth_authorization_codes_code_active
  ON altalune_oauth_authorization_codes (code)
  WHERE exchange_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_oauth_authorization_codes_client_id
  ON altalune_oauth_authorization_codes (client_id);

CREATE INDEX IF NOT EXISTS idx_oauth_authorization_codes_user_id
  ON altalune_oauth_authorization_codes (user_id);

-- Index for cleanup of expired codes
CREATE INDEX IF NOT EXISTS idx_oauth_authorization_codes_expires_at
  ON altalune_oauth_authorization_codes (expires_at)
  WHERE exchange_at IS NULL;

-- -----------------------------------------------------------------------------
-- oauth_refresh_tokens (GLOBAL)
-- -----------------------------------------------------------------------------
-- Stores long-lived refresh tokens for obtaining new access tokens
-- Soft-delete pattern: exchange_at timestamp marks when token was refreshed
CREATE TABLE IF NOT EXISTS altalune_oauth_refresh_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token UUID NOT NULL UNIQUE,
  client_id UUID NOT NULL,
  user_id BIGINT NOT NULL,
  scope TEXT NOT NULL,
  nonce VARCHAR(100),
  expires_at TIMESTAMPTZ NOT NULL,
  exchange_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES altalune_users (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_oauth_refresh_tokens_token
  ON altalune_oauth_refresh_tokens (token);

-- Partial index for active (non-exchanged) tokens only
CREATE INDEX IF NOT EXISTS idx_oauth_refresh_tokens_token_active
  ON altalune_oauth_refresh_tokens (token)
  WHERE exchange_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_oauth_refresh_tokens_client_id
  ON altalune_oauth_refresh_tokens (client_id);

CREATE INDEX IF NOT EXISTS idx_oauth_refresh_tokens_user_id
  ON altalune_oauth_refresh_tokens (user_id);

-- Index for cleanup of expired tokens
CREATE INDEX IF NOT EXISTS idx_oauth_refresh_tokens_expires_at
  ON altalune_oauth_refresh_tokens (expires_at)
  WHERE exchange_at IS NULL;

-- -----------------------------------------------------------------------------
-- oauth_user_consents (GLOBAL)
-- -----------------------------------------------------------------------------
-- Tracks which users have granted consent to which clients
-- Allows "remember my choice" functionality
CREATE TABLE IF NOT EXISTS altalune_oauth_user_consents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  client_id UUID NOT NULL,
  scope TEXT NOT NULL,
  granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES altalune_users (id) ON DELETE CASCADE
);

-- Unique constraint: one consent record per user-client pair
CREATE UNIQUE INDEX IF NOT EXISTS ux_oauth_user_consents_user_client
  ON altalune_oauth_user_consents (user_id, client_id);

CREATE INDEX IF NOT EXISTS idx_oauth_user_consents_user_id
  ON altalune_oauth_user_consents (user_id);

CREATE INDEX IF NOT EXISTS idx_oauth_user_consents_client_id
  ON altalune_oauth_user_consents (client_id);

-- Index for finding active consents
CREATE INDEX IF NOT EXISTS idx_oauth_user_consents_active
  ON altalune_oauth_user_consents (user_id, client_id)
  WHERE revoked_at IS NULL;

-- -----------------------------------------------------------------------------
-- Modify project_members table (exists from 20260105000000_create_iam_tables.sql)
-- -----------------------------------------------------------------------------
-- Add public_id column for nanoid support
-- Update role constraint to include 'user' role (OAuth users with no dashboard access)
-- Note: Existing roles are 'owner', 'admin', 'member', 'viewer'
--       We're adding 'user' and keeping 'viewer' for backwards compatibility

-- Add public_id column if it doesn't exist
ALTER TABLE altalune_project_members
  ADD COLUMN IF NOT EXISTS public_id VARCHAR(20);

-- Create unique index on public_id (only if column was just added)
CREATE UNIQUE INDEX IF NOT EXISTS ux_project_members_public_id
  ON altalune_project_members (public_id)
  WHERE public_id IS NOT NULL;

-- Drop old constraint and create new one with both 'viewer' and 'user'
-- viewer: legacy role (kept for backwards compatibility)
-- user: OAuth user with no dashboard access (new)
ALTER TABLE altalune_project_members
  DROP CONSTRAINT IF EXISTS chk_project_members_role;

ALTER TABLE altalune_project_members
  ADD CONSTRAINT chk_project_members_role
    CHECK (role IN ('owner', 'admin', 'member', 'viewer', 'user'));

-- -----------------------------------------------------------------------------
-- Modify user_identities table
-- -----------------------------------------------------------------------------
-- Add oauth_client_id to track which OAuth client the user signed up through
-- Add origin_oauth_client_name to preserve client name as historical metadata
-- (No FK constraint on oauth_client_id to allow client deletion without affecting users)
-- Add last_login_at to track last login timestamp
-- Add first_name and last_name for OAuth user profile data
ALTER TABLE altalune_user_identities
  ADD COLUMN IF NOT EXISTS oauth_client_id UUID,
  ADD COLUMN IF NOT EXISTS origin_oauth_client_name VARCHAR(100),
  ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS first_name VARCHAR(100),
  ADD COLUMN IF NOT EXISTS last_name VARCHAR(100);

CREATE INDEX IF NOT EXISTS idx_user_identities_oauth_client_id
  ON altalune_user_identities (oauth_client_id);

CREATE INDEX IF NOT EXISTS idx_user_identities_last_login_at
  ON altalune_user_identities (last_login_at);

-- =============================================================================
-- SEED STANDARD OAUTH SCOPES
-- =============================================================================
-- Insert standard OAuth 2.0 / OIDC scopes
-- These are required for OAuth server functionality
-- Custom scopes can be added later via application
INSERT INTO altalune_oauth_scopes (public_id, name, description, is_standard)
VALUES
  ('scope_openid_std', 'openid', 'OpenID Connect authentication', true),
  ('scope_profile_std', 'profile', 'Access to user profile information (name, etc.)', true),
  ('scope_email_std', 'email', 'Access to user email address', true),
  ('scope_offline_std', 'offline_access', 'Request refresh token for offline access', true)
ON CONFLICT (name) DO NOTHING;

-- =============================================================================
-- NOTES:
-- =============================================================================
-- 1. oauth_clients and oauth_client_scopes are GLOBAL (not partitioned)
--    OAuth clients are infrastructure-level (like Auth0 Applications), not
--    project-scoped business data. This follows Keycloak/Auth0 patterns.
-- 2. Authorization codes and refresh tokens are GLOBAL (not partitioned)
--    because they represent cross-project user identity
-- 3. Client secrets are hashed with bcrypt (cost 12+) before storage
--    This is different from OAuth PROVIDER secrets which use AES-256-GCM
-- 4. Soft-delete pattern (exchange_at) preserves audit trail
-- 5. PKCE support is optional per client via pkce_required flag
-- 6. Default dashboard client should have pkce_required = true (public client)
-- 7. project_members.role hierarchy:
--    - owner: Superadmin only, full access, auto-assigned to new projects
--    - admin: Manage project (except delete), manage members
--    - member: Access project data, read-only settings
--    - user: OAuth user only, no dashboard access unless upgraded
-- 8. user_identities.oauth_client_id tracks which client the user signed up
--    through (historical metadata, no FK constraint to allow client deletion)
-- 9. user_identities.origin_oauth_client_name stores client name at signup time
--    as a snapshot for historical tracking purposes
-- =============================================================================

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

-- Drop in reverse order of creation to handle foreign key dependencies

-- Revert user_identities alterations
ALTER TABLE altalune_user_identities
  DROP COLUMN IF EXISTS oauth_client_id,
  DROP COLUMN IF EXISTS origin_oauth_client_name,
  DROP COLUMN IF EXISTS last_login_at,
  DROP COLUMN IF EXISTS first_name,
  DROP COLUMN IF EXISTS last_name;

-- Revert project_members alterations
-- Drop the unique index on public_id
DROP INDEX IF EXISTS ux_project_members_public_id;

-- Remove public_id column
ALTER TABLE altalune_project_members
  DROP COLUMN IF EXISTS public_id;

-- Revert role constraint to original (owner, admin, member, viewer)
ALTER TABLE altalune_project_members
  DROP CONSTRAINT IF EXISTS chk_project_members_role;

ALTER TABLE altalune_project_members
  ADD CONSTRAINT chk_project_members_role
    CHECK (role IN ('owner', 'admin', 'member', 'viewer'));

-- Drop OAuth tables (NOT project_members since it existed before)
DROP TABLE IF EXISTS altalune_oauth_user_consents;
DROP TABLE IF EXISTS altalune_oauth_refresh_tokens;
DROP TABLE IF EXISTS altalune_oauth_authorization_codes;
DROP TABLE IF EXISTS altalune_oauth_client_scopes;
DROP TABLE IF EXISTS altalune_oauth_clients;
DROP TABLE IF EXISTS altalune_oauth_scopes;

-- +goose StatementEnd
