-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS altalune_chatbot_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  public_id VARCHAR(20) NOT NULL,
  project_id BIGINT NOT NULL,
  modules_config JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (project_id, id),
  CONSTRAINT fk_altalune_chatbot_configs_project_id
    FOREIGN KEY (project_id) REFERENCES altalune_projects (id)
    ON DELETE CASCADE ON UPDATE CASCADE
) PARTITION BY LIST (project_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_altalune_chatbot_configs_public_id
  ON altalune_chatbot_configs (project_id, public_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_altalune_chatbot_configs_project_id
  ON altalune_chatbot_configs (project_id);

-- Create partitions for all existing projects
DO $$
DECLARE
  proj RECORD;
BEGIN
  FOR proj IN SELECT id FROM altalune_projects LOOP
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS altalune_chatbot_configs_p%s PARTITION OF altalune_chatbot_configs FOR VALUES IN (%s)',
      proj.id, proj.id
    );
  END LOOP;
END $$;
-- +goose StatementEnd

-- Note: Partitions are created in two ways:
-- - Existing projects: Created by the DO block above during migration
-- - New projects: Created by project/repo.go createPartitionsForProject()

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS altalune_chatbot_configs CASCADE;
-- +goose StatementEnd
