-- +goose Up
-- +goose StatementBegin

-- =============================================================================
-- OAUTH PROVIDER TABLES (GLOBAL - NON-PARTITIONED)
-- =============================================================================
-- CRITICAL: These tables are GLOBAL and do NOT include project_id columns.
-- OAuth providers are system-wide configuration, not per-project.
-- This design decision means:
--   - Only one OAuth provider configuration per provider type (e.g., one Google)
--   - All projects use the same OAuth providers
--   - Credentials are stored globally with encryption
-- =============================================================================

-- -----------------------------------------------------------------------------
-- altalune_oauth_providers
-- -----------------------------------------------------------------------------
-- Stores OAuth provider configurations (Google, Github, Microsoft, Apple)
-- Client secrets are encrypted at rest using AES-256-GCM
-- Only one provider per provider_type allowed (UNIQUE constraint)
-- This table is referenced by altalune_user_identities (created in US3)
CREATE TABLE IF NOT EXISTS altalune_oauth_providers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(20) NOT NULL UNIQUE,
  provider_type VARCHAR(20) NOT NULL UNIQUE,
  client_id VARCHAR(500) NOT NULL,
  client_secret TEXT NOT NULL,
  redirect_url VARCHAR(500) NOT NULL,
  scopes VARCHAR(1000),
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_oauth_providers_type CHECK (
    provider_type IN ('google', 'github', 'microsoft', 'apple')
  )
);

-- Indexes for oauth_providers table
-- UNIQUE on public_id for API lookups
CREATE UNIQUE INDEX IF NOT EXISTS ux_oauth_providers_public_id
  ON altalune_oauth_providers (public_id);

-- UNIQUE on provider_type to enforce one provider per type
CREATE UNIQUE INDEX IF NOT EXISTS ux_oauth_providers_provider_type
  ON altalune_oauth_providers (provider_type);

-- INDEX on enabled for filtering active providers
CREATE INDEX IF NOT EXISTS idx_oauth_providers_enabled
  ON altalune_oauth_providers (enabled);

-- =============================================================================
-- NOTES:
-- =============================================================================
-- 1. altalune_user_identities table already exists from migration
--    20260105000000_create_iam_tables.sql and is NOT managed here
-- 2. client_secret is stored as TEXT (not VARCHAR) because encrypted
--    ciphertext (AES-256-GCM + base64) can exceed VARCHAR(500)
-- 3. provider_type UNIQUE constraint is CRITICAL - only one provider
--    configuration per type is allowed
-- 4. CHECK constraint validates provider_type enum values
-- 5. Encryption/decryption is handled at application layer, not database
-- =============================================================================

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP TABLE IF EXISTS altalune_oauth_providers;

-- +goose StatementEnd
